### ISSUE TITLE
Please add  Admin panel simple .

### ISSUE THREAD

**Issue by eArabic** [gothx2009/MyForum#1]
Hello my friend
Thank you very much for the excellent excellent script, its very beautiful idea simple and fast.
Please add some necessary features such as a simple control panel to control deletion, modification, etc.
As well as add these features:
  - Admin panel simple .
  - Search.
  - Images and files upload.
  - Pagination.
  - Categories.
  - Locked and sticky posts  settings.
  - Settings : Control some features such as number of posts on the page and other disabled or activate certain features.
  - Add a user name to see the post author, as well as when you reply, not the registration requirement.
Thank you very much for sharing this wonderful script.

**Comment by gothx2009** [comment]
I'll just leave this here for reference:

- [ ] Pagination (Completed: 50%)
- [x] Locked Topics
- [x] Pinned / Sticky Topics
- [x] Topic Deletion
- [x] Post Deletion 
- [x] Forum Settings / Configuration File
- [x] Optional author display name

**Comment by eArabic** [comment]
Dear Friend
I will wait for any updates from you.
Thank you so much

**Comment by gothx2009** [comment]
A number of your requests have been addressed and included in the official **PRE-RELEASE** version `0.5.0`

**Comment by eArabic** [comment]
Thank you so much my dear friend
But unfortunately did not work for me and I do not know what is the reason and what is the solution.
Is it possible to upload the database  sql file.
Thank you very much for the update and wait for my problem to be resolved.

![eee](https://user-images.githubusercontent.com/24383546/34096615-16119020-e3e7-11e7-8ae8-5cc351281bcd.png)

**Comment by eArabic** [comment]
Hello dear friend
You have manually added the database to work now.
Thank you very much. It is very excellent and I am waiting for the rest of the updates.

**Comment by gothx2009** [comment]
Everything except pagination on the topic list and locked topics have been added in the official **PRE-RELEASE** version `0.7.0`

**Comment by eArabic** [comment]
Hello dear friend
Thanks so much for the updates.
It is now better.
Please You can add a simple WYSIWYG editor and make it acceptable to embed images In the Topics.
Thank you so much

**Comment by eArabic** [comment]
Hello dear friend
I am following each update, and I am still waiting for the update and final release.
Thank you so much .
