### ISSUE TITLE
 Not delete the post

### ISSUE THREAD

**Issue by Arabiain** [gothx2009/MyForum#10]
![مشكلة الحذف](https://user-images.githubusercontent.com/8568779/94376296-6500d000-0122-11eb-887f-7f9803727ad0.jpg)
 problem that I cannot use the delete

There is a problem that I cannot use the delete feature, as it does not delete the post, what is the reason ?!

_Originally posted by @Arabiain in https://github.com/gothx2009/MyForum/issues/8#issuecomment-699691153_

**Comment by gothx2009** [comment]
Whoops.  Thought I fixed that.  It's pulling the wrong ID.

I'm working on the new fix now.
